/* _GlobalPrefix_ */
"use strict";this.default_host=this.default_host||{};(function(_){var window=this;
/* _Module_:ultraviolet_base_module */
try{
_.aa=_.aa||{};_.k=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
/* _Module_:sy0 */
try{
var la,ma;_.p=function(a){return void 0!==a};_.q=function(a){return"string"==typeof a};_.ca=function(a){return"number"==typeof a};_.da=function(a){a=a.split(".");for(var b=_.k,c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b};_.ea=function(){};
_.fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.ha=function(a){return"array"==_.fa(a)};_.ia=function(a){var b=_.fa(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.ja=function(a){return"function"==_.fa(a)};_.ka=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};la=function(a,b,c){return a.call.apply(a.bind,arguments)};
ma=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.t=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?_.t=la:_.t=ma;return _.t.apply(null,arguments)};
_.na=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.oa=function(a,b){a=a.split(".");var c=_.k;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&_.p(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}};
_.u=function(a,b){function c(){}c.prototype=b.prototype;a.w=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Pc=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.pa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.pa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.u(_.pa,Error);_.pa.prototype.name="CustomError";var qa;qa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(_.q(a))return _.q(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.v=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.q(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.ra=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f=_.q(a)?a.split(""):a,h=0;h<c;h++)if(h in f){var l=f[h];b.call(void 0,l,h,a)&&(d[e++]=l)}return d};_.sa=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e=_.q(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d};
_.ta=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.q(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.va=function(a,b){b=_.ua(a,b,void 0);return 0>b?null:_.q(a)?a.charAt(b):a[b]};_.ua=function(a,b,c){for(var d=a.length,e=_.q(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};_.wa=function(a,b){return 0<=qa(a,b)};_.ya=function(a,b){b=qa(a,b);var c;(c=0<=b)&&_.xa(a,b);return c}; _.xa=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.za=function(a){return Array.prototype.concat.apply([],arguments)};_.Aa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
var Fa,Ha;_.Ba=function(a,b){return 0==a.lastIndexOf(b,0)};_.Ca=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.Da=function(a){return/^[\s\xa0]*$/.test(a)};_.Ea=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};Fa=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};_.Ga=function(a){return null==a?"":String(a)};
_.Ia=function(a,b){var c=0;a=(0,_.Ea)(String(a)).split(".");b=(0,_.Ea)(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",h=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;c=Ha(0==f[1].length?0:(0,window.parseInt)(f[1],10),0==h[1].length?0:(0,window.parseInt)(h[1],10))||Ha(0==f[2].length,0==h[2].length)||Ha(f[2],h[2]);f=f[3];h=h[3]}while(0==c)}return c}; Ha=function(a,b){return a<b?-1:a>b?1:0};
a:{var Ka=_.k.navigator;if(Ka){var La=Ka.userAgent;if(La){_.Ja=La;break a}}_.Ja=""}_.x=function(a){return-1!=_.Ja.indexOf(a)};var Na,Pa;_.Ma=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Na=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};_.Oa=function(a){var b={},c;for(c in a)b[c]=a[c];return b};Pa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");_.Qa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Pa.length;f++)c=Pa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
_.Ra=function(){return _.x("Trident")||_.x("MSIE")};_.Ta=function(){return _.x("Safari")&&!(_.Sa()||_.x("Coast")||_.x("Opera")||_.x("Edge")||_.x("Silk")||_.x("Android"))};_.Sa=function(){return(_.x("Chrome")||_.x("CriOS"))&&!_.x("Edge")};var Ua,Va;Ua=function(){return _.x("iPhone")&&!_.x("iPod")&&!_.x("iPad")};Va=function(){return Ua()||_.x("iPad")||_.x("iPod")};_.Wa=function(){return _.x("Macintosh")};_.Xa=function(){return _.x("Windows")};_.Ya=function(){return _.x("CrOS")};var Za=function(a){Za[" "](a);return a};Za[" "]=_.ea;_.$a=function(a,b){try{return Za(a[b]),!0}catch(c){}return!1};_.ab=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};var bb,eb,ib,lb,mb,qb,rb,tb;bb=_.x("Opera");_.cb=_.Ra();eb=_.x("Edge");_.fb=_.x("Gecko")&&!(-1!=_.Ja.toLowerCase().indexOf("webkit")&&!_.x("Edge"))&&!(_.x("Trident")||_.x("MSIE"))&&!_.x("Edge");_.gb=-1!=_.Ja.toLowerCase().indexOf("webkit")&&!_.x("Edge");ib=_.k.navigator||null;_.hb=ib&&ib.platform||"";_.jb=_.Wa();_.kb=_.Xa();lb=function(){var a=_.k.document;return a?a.documentMode:void 0};
a:{var nb="",ob=function(){var a=_.Ja;if(_.fb)return/rv:([^\);]+)(\)|;)/.exec(a);if(eb)return/Edge\/([\d\.]+)/.exec(a);if(_.cb)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.gb)return/WebKit\/(\S+)/.exec(a);if(bb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ob&&(nb=ob?ob[1]:"");if(_.cb){var pb=lb();if(null!=pb&&pb>(0,window.parseFloat)(nb)){mb=String(pb);break a}}mb=nb}qb=mb;rb={};_.sb=function(a){return _.ab(rb,a,function(){return 0<=_.Ia(qb,a)})};var ub=_.k.document; tb=ub&&_.cb?lb()||("CSS1Compat"==ub.compatMode?(0,window.parseInt)(qb,10):5):void 0;
var vb=_.x("Firefox"),wb=Ua()||_.x("iPod"),xb=_.x("iPad"),yb=_.x("Android")&&!(_.Sa()||_.x("Firefox")||_.x("Opera")||_.x("Silk")),zb=_.Sa(),Ab=_.Ta()&&!Va();var Bb=null;var Eb,Gb;_.y=function(){};_.Cb="function"==typeof window.Uint8Array;
_.B=function(a,b,c,d,e){a.a=null;b||(b=c?[c]:[]);a.l=c?String(c):void 0;a.c=0===c?-1:0;a.b=b;a:{if(b=a.b.length)if(--b,(c=a.b[b])&&"object"==typeof c&&!_.ha(c)&&!(_.Cb&&c instanceof window.Uint8Array)){a.h=b-a.c;a.g=c;break a}a.h=Number.MAX_VALUE}a.j={};if(d)for(b=0;b<d.length;b++)c=d[b],c<a.h?(c+=a.c,a.b[c]=a.b[c]||_.Db):(Eb(a),a.g[c]=a.g[c]||_.Db);if(e&&e.length)for(b=0;b<e.length;b++){c=d=void 0;for(var f=a,h=e[b],l=0;l<h.length;l++){var n=h[l],r=_.z(f,n);null!=r&&(c=n,d=r,_.A(f,n,void 0))}c&&
_.A(f,c,d)}};_.Db=[];Eb=function(a){var b=a.h+a.c;a.b[b]||(a.g=a.b[b]={})};_.z=function(a,b){if(b<a.h){b+=a.c;var c=a.b[b];return c===_.Db?a.b[b]=[]:c}if(a.g)return c=a.g[b],c===_.Db?a.g[b]=[]:c};_.Fb=function(a,b,c){a=_.z(a,b);return null==a?c:a};_.A=function(a,b,c){b<a.h?a.b[b+a.c]=c:(Eb(a),a.g[b]=c)};_.C=function(a,b,c){a.a||(a.a={});if(!a.a[c]){var d=_.z(a,c);d&&(a.a[c]=new b(d))}return a.a[c]};_.E=function(a,b,c){a.a||(a.a={});var d=c?_.D(c):c;a.a[b]=c;_.A(a,b,d)};
Gb=function(a){if(a.a)for(var b in a.a){var c=a.a[b];if(_.ha(c))for(var d=0;d<c.length;d++)c[d]&&_.D(c[d]);else c&&_.D(c)}};_.D=function(a){Gb(a);return a.b};
_.y.prototype.C=_.Cb?function(){var a=window.Uint8Array.prototype.toJSON;window.Uint8Array.prototype.toJSON=function(){if(!Bb){Bb={};for(var a=0;65>a;a++)Bb[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}a=Bb;for(var c=[],d=0;d<this.length;d+=3){var e=this[d],f=d+1<this.length,h=f?this[d+1]:0,l=d+2<this.length,n=l?this[d+2]:0,r=e>>2;e=(e&3)<<4|h>>4;h=(h&15)<<2|n>>6;n&=63;l||(n=64,f||(h=64));c.push(a[r],a[e],a[h],a[n])}return c.join("")};try{return JSON.stringify(this.b&&
_.D(this),Hb)}finally{window.Uint8Array.prototype.toJSON=a}}:function(){return JSON.stringify(this.b&&_.D(this),Hb)};var Hb=function(a,b){return _.ca(b)&&((0,window.isNaN)(b)||window.Infinity===b||-window.Infinity===b)?String(b):b};_.y.prototype.toString=function(){Gb(this);return this.b.toString()};
_.F=function(){this.G=this.G;this.C=this.C};_.F.prototype.G=!1;_.F.prototype.$=function(){this.G||(this.G=!0,this.v())};_.I=function(a,b){_.G(a,_.na(_.H,b))};_.G=function(a,b,c){a.G?_.p(c)?b.call(c):b():(a.C||(a.C=[]),a.C.push(_.p(c)?(0,_.t)(b,c):b))};_.F.prototype.v=function(){if(this.C)for(;this.C.length;)this.C.shift()()};_.H=function(a){a&&"function"==typeof a.$&&a.$()};
var Ib=function(a,b){this.g=a;this.c=b;this.b=0;this.a=null};Ib.prototype.get=function(){if(0<this.b){this.b--;var a=this.a;this.a=a.next;a.next=null}else a=this.g();return a};var Jb=function(a,b){a.c(b);100>a.b&&(a.b++,b.next=a.a,a.a=b)};var Nb;_.Kb=[];_.Lb=[];_.Mb=!1;Nb=function(a){_.Kb[_.Kb.length]=a;if(_.Mb)for(var b=0;b<_.Lb.length;b++)a((0,_.t)(_.Lb[b].b,_.Lb[b]))};_.Ob=function(a){return function(){return a}}(!1);var Pb,Rb,Sb,Qb;Pb=function(a){_.k.setTimeout(function(){throw a;},0)};_.Tb=function(a,b){var c=a;b&&(c=(0,_.t)(a,b));c=Qb(c);!_.ja(_.k.setImmediate)||_.k.Window&&_.k.Window.prototype&&!_.x("Edge")&&_.k.Window.prototype.setImmediate==_.k.setImmediate?(Rb||(Rb=Sb()),Rb(c)):_.k.setImmediate(c)};
Sb=function(){var a=_.k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.x("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow;a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host;a=(0,_.t)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.Ra()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.p(c.next)){c=c.next;var a=c.tb;c.tb=null;a()}};return function(a){d.next={tb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT"); b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.k.setTimeout(a,0)}};Qb=function(a){return a};Nb(function(a){Qb=a});
var Ub=function(){this.b=this.a=null},Wb=new Ib(function(){return new Vb},function(a){a.reset()});Ub.prototype.add=function(a,b){var c=Wb.get();c.set(a,b);this.b?this.b.next=c:this.a=c;this.b=c};Ub.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var Vb=function(){this.next=this.b=this.a=null};Vb.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};Vb.prototype.reset=function(){this.next=this.b=this.a=null};
var ac=function(a,b){Xb||Yb();Zb||(Xb(),Zb=!0);$b.add(a,b)},Xb,Yb=function(){if(_.k.Promise&&_.k.Promise.resolve){var a=_.k.Promise.resolve(void 0);Xb=function(){a.then(bc)}}else Xb=function(){_.Tb(bc)}},Zb=!1,$b=new Ub,bc=function(){for(var a;a=$b.remove();){try{a.a.call(a.b)}catch(b){Pb(b)}Jb(Wb,a)}Zb=!1};
var cc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},dc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var gc,hc,ic,nc,rc,sc,qc,oc;_.fc=function(a,b){this.a=0;this.j=void 0;this.c=this.b=this.g=null;this.h=this.C=!1;if(a!=_.ea)try{var c=this;a.call(b,function(a){_.ec(c,2,a)},function(a){_.ec(c,3,a)})}catch(d){_.ec(this,3,d)}};gc=function(){this.next=this.c=this.b=this.h=this.a=null;this.g=!1};gc.prototype.reset=function(){this.c=this.b=this.h=this.a=null;this.g=!1};hc=new Ib(function(){return new gc},function(a){a.reset()});ic=function(a,b,c){var d=hc.get();d.h=a;d.b=b;d.c=c;return d};
_.kc=function(){var a,b=new _.fc(function(b){a=b});return new jc(b,a)};_.fc.prototype.then=function(a,b,c){return _.lc(this,_.ja(a)?a:null,_.ja(b)?b:null,c)};cc(_.fc);_.fc.prototype.cancel=function(a){0==this.a&&ac(function(){var b=new mc(a);nc(this,b)},this)};
nc=function(a,b){if(0==a.a)if(a.g){var c=a.g;if(c.b){for(var d=0,e=null,f=null,h=c.b;h&&(h.g||(d++,h.a==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.a&&1==d?nc(c,b):(f?(d=f,d.next==c.c&&(c.c=d),d.next=d.next.next):oc(c),pc(c,e,3,b)))}a.g=null}else _.ec(a,3,b)};rc=function(a,b){a.b||2!=a.a&&3!=a.a||qc(a);a.c?a.c.next=b:a.b=b;a.c=b};
_.lc=function(a,b,c,d){var e=ic(null,null,null);e.a=new _.fc(function(a,h){e.h=b?function(c){try{var e=b.call(d,c);a(e)}catch(r){h(r)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.p(e)&&b instanceof mc?h(b):a(e)}catch(r){h(r)}}:h});e.a.g=a;rc(a,e);return e.a};_.fc.prototype.m=function(a){this.a=0;_.ec(this,2,a)};_.fc.prototype.o=function(a){this.a=0;_.ec(this,3,a)};
_.ec=function(a,b,c){if(0==a.a){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.a=1;a:{var d=c,e=a.m,f=a.o;if(d instanceof _.fc){rc(d,ic(e||_.ea,f||null,a));var h=!0}else if(dc(d))d.then(e,f,a),h=!0;else{if(_.ka(d))try{var l=d.then;if(_.ja(l)){sc(d,l,e,f,a);h=!0;break a}}catch(n){f.call(a,n);h=!0;break a}h=!1}}h||(a.j=c,a.a=b,a.g=null,qc(a),3!=b||c instanceof mc||tc(a,c))}};
sc=function(a,b,c,d,e){var f=!1,h=function(a){f||(f=!0,c.call(e,a))},l=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,h,l)}catch(n){l(n)}};qc=function(a){a.C||(a.C=!0,ac(a.l,a))};oc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.c=null);return b};_.fc.prototype.l=function(){for(var a;a=oc(this);)pc(this,a,this.a,this.j);this.C=!1};
var pc=function(a,b,c,d){if(3==c&&b.b&&!b.g)for(;a&&a.h;a=a.g)a.h=!1;if(b.a)b.a.g=null,uc(b,c,d);else try{b.g?b.h.call(b.c):uc(b,c,d)}catch(e){vc.call(null,e)}Jb(hc,b)},uc=function(a,b,c){2==b?a.h.call(a.c,c):a.b&&a.b.call(a.c,c)},tc=function(a,b){a.h=!0;ac(function(){a.h&&vc.call(null,b)})},vc=Pb,mc=function(a){_.pa.call(this,a)};_.u(mc,_.pa);mc.prototype.name="cancel";var jc=function(a,b){this.a=a;this.b=b};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.wc=function(a,b){this.l=[];this.L=a;this.A=b||null;this.C=this.c=!1;this.h=void 0;this.F=this.J=this.o=!1;this.m=0;this.a=null;this.j=0};_.wc.prototype.cancel=function(a){if(this.c)this.h instanceof _.wc&&this.h.cancel();else{if(this.a){var b=this.a;delete this.a;a?b.cancel(a):(b.j--,0>=b.j&&b.cancel())}this.L?this.L.call(this.A,this):this.F=!0;this.c||this.D(new _.xc(this))}};_.wc.prototype.I=function(a,b){this.o=!1;yc(this,a,b)};
var yc=function(a,b,c){a.c=!0;a.h=c;a.C=!b;zc(a)},Bc=function(a){if(a.c){if(!a.F)throw new Ac(a);a.F=!1}};_.wc.prototype.g=function(a){Bc(this);yc(this,!0,a)};_.wc.prototype.D=function(a){Bc(this);yc(this,!1,a)};_.Dc=function(a,b,c){_.Cc(a,b,null,c)};_.Cc=function(a,b,c,d){a.l.push([b,c,d]);a.c&&zc(a)};_.wc.prototype.then=function(a,b,c){var d,e,f=new _.fc(function(a,b){d=a;e=b});_.Cc(this,d,function(a){a instanceof _.xc?f.cancel():e(a)});return f.then(a,b,c)};cc(_.wc);
_.wc.prototype.b=function(a){var b=new _.wc;_.Cc(this,b.g,b.D,b);a&&(b.a=this,this.j++);return b};_.wc.prototype.isError=function(a){return a instanceof Error};
var Ec=function(a){return(0,_.ta)(a.l,function(a){return _.ja(a[1])})},zc=function(a){if(a.m&&a.c&&Ec(a)){var b=a.m,c=Fc[b];c&&(_.k.clearTimeout(c.a),delete Fc[b]);a.m=0}a.a&&(a.a.j--,delete a.a);b=a.h;for(var d=c=!1;a.l.length&&!a.o;){var e=a.l.shift(),f=e[0],h=e[1];e=e[2];if(f=a.C?h:f)try{var l=f.call(e||a.A,b);_.p(l)&&(a.C=a.C&&(l==b||a.isError(l)),a.h=b=l);if(dc(b)||"function"===typeof _.k.Promise&&b instanceof _.k.Promise)d=!0,a.o=!0}catch(n){b=n,a.C=!0,Ec(a)||(c=!0)}}a.h=b;d&&(l=(0,_.t)(a.I,
a,!0),d=(0,_.t)(a.I,a,!1),b instanceof _.wc?(_.Cc(b,l,d),b.J=!0):b.then(l,d));c&&(b=new Gc(b),Fc[b.a]=b,a.m=b.a)},Ac=function(){_.pa.call(this)};_.u(Ac,_.pa);Ac.prototype.message="Deferred has already fired";Ac.prototype.name="AlreadyCalledError";_.xc=function(){_.pa.call(this)};_.u(_.xc,_.pa);_.xc.prototype.message="Deferred was canceled";_.xc.prototype.name="CanceledError";var Gc=function(a){this.a=_.k.setTimeout((0,_.t)(this.g,this),0);this.b=a}; Gc.prototype.g=function(){delete Fc[this.a];throw this.b;};var Fc={};
var Hc=!_.fb&&!_.cb||_.cb&&9<=Number(tb)||_.fb&&_.sb("1.9.1");_.Ic=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;_.Kc=function(){this.b="";this.g=_.Jc};_.Kc.prototype.Da=!0;_.Kc.prototype.Aa=function(){return this.b};_.Kc.prototype.kb=!0;_.Kc.prototype.a=function(){return 1};_.Jc={};_.Lc=function(a){var b=new _.Kc;b.b=a;return b};_.Lc("about:blank");_.Nc=function(){this.b="";this.c=_.Mc;this.g=null};_.Nc.prototype.kb=!0;_.Nc.prototype.a=function(){return this.g};_.Nc.prototype.Da=!0;_.Nc.prototype.Aa=function(){return this.b};_.Mc={};_.Oc=function(a,b){var c=new _.Nc;c.b=a;c.g=b;return c};_.Oc("<!DOCTYPE html>",0);_.Oc("",0);_.Pc=_.Oc("<br>",0);
var Sc;_.Rc=function(a,b){var c=b||window.document;if(c.getElementsByClassName)a=c.getElementsByClassName(a)[0];else{c=window.document;var d=b||c;a=d.querySelectorAll&&d.querySelector&&a?d.querySelector(a?"."+a:""):_.Qc(c,"*",a,b)[0]||null}return a||null};
_.Qc=function(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&_.wa(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a};
_.Tc=function(a,b){_.Ma(b,function(b,d){b&&b.Da&&(b=b.Aa());"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Sc.hasOwnProperty(d)?a.setAttribute(Sc[d],b):_.Ba(d,"aria-")||_.Ba(d,"data-")?a.setAttribute(d,b):a[d]=b})};Sc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
_.Uc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.Vc=function(a){this.a=a||_.k.document||window.document};_.Vc.prototype.B=function(a){return _.q(a)?this.a.getElementById(a):a};_.Vc.prototype.setProperties=_.Tc;_.Wc=function(a,b){return a.a.createElement(String(b))};_.Vc.prototype.getChildren=function(a){return Hc&&void 0!=a.children?a.children:(0,_.ra)(a.childNodes,function(a){return 1==a.nodeType})};
_.Vc.prototype.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
var Yc,Xc,ad,bd,$c;_.Zc=function(a){var b=[];Xc(new Yc,a,b);return b.join("")};Yc=function(){};
Xc=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.ha(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),Xc(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),$c(d,c),c.push(":"),Xc(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":$c(b,c);break;case "number":c.push((0,window.isFinite)(b)&&
!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("d`"+typeof b);}}};ad={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};bd=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g;$c=function(a,b){b.push('"',a.replace(bd,function(a){var b=ad[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),ad[a]=b);return b}),'"')};
var cd="StopIteration"in _.k?_.k.StopIteration:{message:"StopIteration",stack:""},dd=function(){};dd.prototype.next=function(){throw cd;};dd.prototype.ia=function(){return this};
var ed=function(a){if(a instanceof dd)return a;if("function"==typeof a.ia)return a.ia(!1);if(_.ia(a)){var b=0,c=new dd;c.next=function(){for(;;){if(b>=a.length)throw cd;if(b in a)return a[b++];b++}};return c}throw Error("e");},fd=function(a,b){if(_.ia(a))try{(0,_.v)(a,b,void 0)}catch(c){if(c!==cd)throw c;}else{a=ed(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==cd)throw c;}}},gd=function(a){if(_.ia(a))return _.Aa(a);a=ed(a);var b=[];fd(a,function(a){b.push(a)});return b};
_.J=function(a,b){this.b={};this.a=[];this.c=this.g=0;var c=arguments.length;if(1<c){if(c%2)throw Error("b");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof _.J)for(c=a.X(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])};_.J.prototype.S=function(){hd(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.J.prototype.X=function(){hd(this);return this.a.concat()};_.jd=function(a,b){return id(a.b,b)};
_.J.prototype.clear=function(){this.b={};this.c=this.g=this.a.length=0};_.J.prototype.remove=function(a){return id(this.b,a)?(delete this.b[a],this.g--,this.c++,this.a.length>2*this.g&&hd(this),!0):!1};var hd=function(a){if(a.g!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];id(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.g!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],id(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.J.prototype.get=function(a,b){return id(this.b,a)?this.b[a]:b};
_.J.prototype.set=function(a,b){id(this.b,a)||(this.g++,this.a.push(a),this.c++);this.b[a]=b};_.J.prototype.forEach=function(a,b){for(var c=this.X(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.J.prototype.ia=function(a){hd(this);var b=0,c=this.c,d=this,e=new dd;e.next=function(){if(c!=d.c)throw Error("f");if(b>=d.a.length)throw cd;var e=d.a[b++];return a?e:d.b[e]};return e};var id=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.K=function(a,b){this.type="undefined"!=typeof _.kd&&a instanceof _.kd?String(a):a;this.b=this.target=b;this.c=!1;this.yb=!0};_.K.prototype.h=function(){this.c=!0};_.K.prototype.g=function(){this.yb=!1};var ld=!_.cb||9<=Number(tb),md=_.cb&&!_.sb("9"),nd=function(){if(!_.k.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});_.k.addEventListener("test",_.ea,b);_.k.removeEventListener("test",_.ea,b);return a}();
var pd=function(a,b){_.K.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;(b=a.relatedTarget)?_.fb&&(_.$a(b,"nodeName")||(b=null)):"mouseover"==c?b=a.fromElement:"mouseout"==
c&&(b=a.toElement);this.relatedTarget=b;null===d?(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=
a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=_.q(a.pointerType)?a.pointerType:od[a.pointerType]||"";this.a=a;a.defaultPrevented&&this.g()}};_.u(pd,_.K);var od={2:"touch",3:"pen",4:"mouse"};pd.prototype.h=function(){pd.w.h.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};pd.prototype.g=function(){pd.w.g.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,md)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var qd,sd;qd="closure_listenable_"+(1E6*Math.random()|0);_.rd=function(a){return!(!a||!a[qd])};sd=0;var td=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.Oa=e;this.key=++sd;this.removed=this.Ma=!1},ud=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Oa=null};var vd=function(a){this.src=a;this.a={};this.b=0},zd,wd;vd.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=wd(a,b,d,e);-1<h?(b=a[h],c||(b.Ma=!1)):(b=new td(b,this.src,f,!!d,e),b.Ma=c,a.push(b));return b};vd.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=wd(e,b,c,d);return-1<b?(ud(e[b]),_.xa(e,b),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var xd=function(a,b){var c=b.type;c in a.a&&_.ya(a.a[c],b)&&(ud(b),0==a.a[c].length&&(delete a.a[c],a.b--))};vd.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,ud(d[e]);delete this.a[c];this.b--}return b};_.yd=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=wd(a,c,d,e));return-1<b?a[b]:null};
zd=function(a){var b=_.p(void 0)?"undefined":void 0,c=_.p(b),d=c?b.toString():"",e=_.p(void 0);return Na(a.a,function(a){for(var b=0;b<a.length;++b)if(!(c&&a[b].type!=d||e&&void 0!=a[b].capture))return!0;return!1})};wd=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.capture==!!c&&f.Oa==d)return e}return-1};
var Ad,Bd,Cd,Gd,Id,Jd,Od,Nd,Kd,Pd;Ad="closure_lm_"+(1E6*Math.random()|0);Bd={};Cd=0;_.Ed=function(a,b,c,d,e){if(d&&d.once)return _.Dd(a,b,c,d,e);if(_.ha(b)){for(var f=0;f<b.length;f++)_.Ed(a,b[f],c,d,e);return null}c=_.Fd(c);return _.rd(a)?a.listen(b,c,_.ka(d)?!!d.capture:!!d,e):Gd(a,b,c,!1,d,e)};
Gd=function(a,b,c,d,e,f){if(!b)throw Error("g");var h=_.ka(e)?!!e.capture:!!e,l=_.Hd(a);l||(a[Ad]=l=new vd(a));c=l.add(b,c,d,h,f);if(c.proxy)return c;d=Id();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)nd||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Jd(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("h");Cd++;return c};
Id=function(){var a=Kd,b=ld?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};_.Dd=function(a,b,c,d,e){if(_.ha(b)){for(var f=0;f<b.length;f++)_.Dd(a,b[f],c,d,e);return null}c=_.Fd(c);return _.rd(a)?a.L(b,c,_.ka(d)?!!d.capture:!!d,e):Gd(a,b,c,!0,d,e)};
_.Ld=function(a,b,c,d,e){if(_.ha(b))for(var f=0;f<b.length;f++)_.Ld(a,b[f],c,d,e);else d=_.ka(d)?!!d.capture:!!d,c=_.Fd(c),_.rd(a)?a.g.remove(String(b),c,d,e):a&&(a=_.Hd(a))&&(b=_.yd(a,b,c,d,e))&&_.Md(b)};
_.Md=function(a){if(!_.ca(a)&&a&&!a.removed){var b=a.src;if(_.rd(b))xd(b.g,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Jd(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Cd--;(c=_.Hd(b))?(xd(c,a),0==c.b&&(c.src=null,b[Ad]=null)):ud(a)}}};Jd=function(a){return a in Bd?Bd[a]:Bd[a]="on"+a};
Od=function(a,b,c,d){var e=!0;if(a=_.Hd(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.removed&&(f=Nd(f,d),e=e&&!1!==f)}return e};Nd=function(a,b){var c=a.listener,d=a.Oa||a.src;a.Ma&&_.Md(a);return c.call(d,b)};
Kd=function(a,b){if(a.removed)return!0;if(!ld){var c=b||_.da("window.event");b=new pd(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.b;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.c&&0<=e;e--){b.b=c[e];var f=Od(c[e],a,!0,b);d=d&&f}for(e=0;!b.c&&e<c.length;e++)b.b=c[e],f=Od(c[e],a,!1,b),d=d&&f}return d}return Nd(a,new pd(b,this))}; _.Hd=function(a){a=a[Ad];return a instanceof vd?a:null};Pd="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Fd=function(a){if(_.ja(a))return a;a[Pd]||(a[Pd]=function(b){return a.handleEvent(b)});return a[Pd]};Nb(function(a){Kd=a(Kd)});
_.L=function(){_.F.call(this);this.g=new vd(this);this.ha=this;this.F=null};_.u(_.L,_.F);_.L.prototype[qd]=!0;_.L.prototype.I=function(a){this.F=a};_.L.prototype.removeEventListener=function(a,b,c,d){_.Ld(this,a,b,c,d)};
_.M=function(a,b){var c,d=a.F;if(d)for(c=[];d;d=d.F)c.push(d);a=a.ha;d=b.type||b;if(_.q(b))b=new _.K(b,a);else if(b instanceof _.K)b.target=b.target||a;else{var e=b;b=new _.K(d,a);_.Qa(b,e)}e=!0;if(c)for(var f=c.length-1;!b.c&&0<=f;f--){var h=b.b=c[f];e=h.oa(d,!0,b)&&e}b.c||(h=b.b=a,e=h.oa(d,!0,b)&&e,b.c||(e=h.oa(d,!1,b)&&e));if(c)for(f=0;!b.c&&f<c.length;f++)h=b.b=c[f],e=h.oa(d,!1,b)&&e;return e};_.L.prototype.v=function(){_.L.w.v.call(this);this.g&&this.g.removeAll(void 0);this.F=null};
_.L.prototype.listen=function(a,b,c,d){return this.g.add(String(a),b,!1,c,d)};_.L.prototype.L=function(a,b,c,d){return this.g.add(String(a),b,!0,c,d)};_.L.prototype.oa=function(a,b,c){a=this.g.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.capture==b){var h=f.listener,l=f.Oa||f.src;f.Ma&&xd(this.g,f);d=!1!==h.call(l,c)&&d}}return d&&0!=c.yb};
var Qd=function(){};Qd.prototype.a=null;var Sd=function(a){var b;(b=a.a)||(b={},Rd(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var Td,Ud=function(){};_.u(Ud,Qd);var Vd=function(a){return(a=Rd(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},Rd=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("i");}return a.b};Td=new Ud;
var Xd;_.Wd=function(a){if(a.S&&"function"==typeof a.S)return a.S();if(_.q(a))return a.split("");if(_.ia(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b};
Xd=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.ia(a)||_.q(a))(0,_.v)(a,b,void 0);else{if(a.X&&"function"==typeof a.X)var c=a.X();else if(a.S&&"function"==typeof a.S)c=void 0;else if(_.ia(a)||_.q(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else for(e in c=[],d=0,a)c[d++]=e;d=_.Wd(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};
_.Yd=function(a,b){_.L.call(this);this.b=a||1;this.a=b||_.k;this.c=(0,_.t)(this.wc,this);this.h=(0,_.m)()};_.u(_.Yd,_.L);_.g=_.Yd.prototype;_.g.qa=!1;_.g.Y=null;_.g.setInterval=function(a){this.b=a;this.Y&&this.qa?(this.stop(),this.start()):this.Y&&this.stop()};_.g.wc=function(){if(this.qa){var a=(0,_.m)()-this.h;0<a&&a<.8*this.b?this.Y=this.a.setTimeout(this.c,this.b-a):(this.Y&&(this.a.clearTimeout(this.Y),this.Y=null),_.M(this,"tick"),this.qa&&(this.Y=this.a.setTimeout(this.c,this.b),this.h=(0,_.m)()))}};
_.g.start=function(){this.qa=!0;this.Y||(this.Y=this.a.setTimeout(this.c,this.b),this.h=(0,_.m)())};_.g.stop=function(){this.qa=!1;this.Y&&(this.a.clearTimeout(this.Y),this.Y=null)};_.g.v=function(){_.Yd.w.v.call(this);this.stop();delete this.a};_.Zd=function(a,b,c){if(_.ja(a))c&&(a=(0,_.t)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.t)(a.handleEvent,a);else throw Error("j");return 2147483647<Number(b)?-1:_.k.setTimeout(a,b||0)};_.$d=function(a){_.k.clearTimeout(a)};
var ae=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,be=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?(0,window.decodeURIComponent)(e.replace(/\+/g," ")):"")}}};
var ce=function(a){_.L.call(this);this.headers=new _.J;this.o=a||null;this.b=!1;this.m=this.a=null;this.J="";this.c=this.D=this.h=this.A=!1;this.l=0;this.j=null;this.W="";this.P=this.N=!1},de,ee,fe,ne,me,je,oe;_.u(ce,_.L);de=/^https?$/i;ee=["POST","PUT"];fe=[];_.ge=function(a,b,c,d,e,f,h){var l=new ce;fe.push(l);b&&l.listen("complete",b);l.L("ready",l.ba);f&&(l.l=Math.max(0,f));h&&(l.N=h);l.send(a,c,d,e)};ce.prototype.ba=function(){this.$();_.ya(fe,this)};
ce.prototype.send=function(a,b,c,d){if(this.a)throw Error("k`"+this.J+"`"+a);b=b?b.toUpperCase():"GET";this.J=a;this.A=!1;this.b=!0;this.a=this.o?Vd(this.o):Vd(Td);this.m=this.o?Sd(this.o):Sd(Td);this.a.onreadystatechange=(0,_.t)(this.V,this);try{this.D=!0,this.a.open(b,String(a),!0),this.D=!1}catch(f){he(this);return}a=c||"";var e=new _.J(this.headers);d&&Xd(d,function(a,b){e.set(b,a)});d=_.va(e.X(),ie);c=_.k.FormData&&a instanceof _.k.FormData;!_.wa(ee,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
e.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.W&&(this.a.responseType=this.W);"withCredentials"in this.a&&this.a.withCredentials!==this.N&&(this.a.withCredentials=this.N);try{je(this),0<this.l&&((this.P=ke(this.a))?(this.a.timeout=this.l,this.a.ontimeout=(0,_.t)(this.T,this)):this.j=_.Zd(this.T,this.l,this)),this.h=!0,this.a.send(a),this.h=!1}catch(f){he(this)}};var ke=function(a){return _.cb&&_.sb(9)&&_.ca(a.timeout)&&_.p(a.ontimeout)},ie=function(a){return"content-type"==a.toLowerCase()};
ce.prototype.T=function(){"undefined"!=typeof _.aa&&this.a&&(_.M(this,"timeout"),this.abort(8))};var he=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);le(a);me(a)},le=function(a){a.A||(a.A=!0,_.M(a,"complete"),_.M(a,"error"))};ce.prototype.abort=function(){this.a&&this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1,_.M(this,"complete"),_.M(this,"abort"),me(this))};ce.prototype.v=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),me(this,!0));ce.w.v.call(this)};
ce.prototype.V=function(){this.G||(this.D||this.h||this.c?ne(this):this.M())};ce.prototype.M=function(){ne(this)};ne=function(a){if(a.b&&"undefined"!=typeof _.aa&&(!a.m[1]||4!=(a.a?a.a.readyState:0)||2!=oe(a)))if(a.h&&4==(a.a?a.a.readyState:0))_.Zd(a.V,0,a);else if(_.M(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{_.pe(a)?(_.M(a,"complete"),_.M(a,"success")):le(a)}finally{me(a)}}};
me=function(a,b){if(a.a){je(a);var c=a.a,d=a.m[0]?_.ea:null;a.a=null;a.m=null;b||_.M(a,"ready");try{c.onreadystatechange=d}catch(e){}}};je=function(a){a.a&&a.P&&(a.a.ontimeout=null);a.j&&(_.$d(a.j),a.j=null)};
_.pe=function(a){var b=oe(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.J).match(ae)[1]||null,!a&&_.k.self&&_.k.self.location&&(a=_.k.self.location.protocol,a=a.substr(0,a.length-1)),b=!de.test(a?a.toLowerCase():"");c=b}return c};oe=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};Nb(function(a){ce.prototype.M=a(ce.prototype.M)});
var re;_.O=function(a){_.F.call(this);this.P=a;this.o={}};_.u(_.O,_.F);var qe=[];_.O.prototype.listen=function(a,b,c,d){_.ha(b)||(b&&(qe[0]=b.toString()),b=qe);for(var e=0;e<b.length;e++){var f=_.Ed(a,b[e],c||this.handleEvent,d||!1,this.P||this);if(!f)break;this.o[f.key]=f}return this};_.se=function(a,b,c,d){re(a,b,c,d,void 0)};re=function(a,b,c,d,e,f){if(_.ha(c))for(var h=0;h<c.length;h++)re(a,b,c[h],d,e,f);else(b=_.Dd(b,c,d||a.handleEvent,e,f||a.P||a))&&(a.o[b.key]=b)}; _.O.prototype.removeAll=function(){_.Ma(this.o,function(a,b){this.o.hasOwnProperty(b)&&_.Md(a)},this);this.o={}};_.O.prototype.v=function(){_.O.w.v.call(this);this.removeAll()};_.O.prototype.handleEvent=function(){throw Error("l");};
_.te=function(a){_.B(this,a,0,null,null)};_.u(_.te,_.y);var ve=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("m");return d.replace(/%([0\- \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,l,n,r,w,N){if("%"==r)return"%";var e=c.shift();if("undefined"==typeof e)throw Error("n");arguments[0]=e;return ue[r].apply(null,arguments)})},ue={s:function(a,b,c){return(0,window.isNaN)(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+Fa(" ",Number(c)-a.length):Fa(" ",Number(c)-a.length)+a},f:function(a,
b,c,d,e){d=a.toString();(0,window.isNaN)(e)||""==e||(d=(0,window.parseFloat)(a).toFixed(e));var f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if((0,window.isNaN)(c)||d.length>=Number(c))return d;d=(0,window.isNaN)(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+Fa(" ",a):f+Fa(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,h,l){return ue.f((0,window.parseInt)(a,10),b,c, d,0,f,h,l)}};ue.i=ue.d;ue.u=ue.d;
_.P=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if(arguments[d]instanceof Error)c.push(arguments[d].stack);else if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(e){c.push("_error_("+e+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=ve("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString(void 0,{hour12:!1})+ve(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+ve.apply({},c)))};
_.xe=function(a){_.B(this,a,"h_exts",we,null)};_.u(_.xe,_.y);var we=[2];_.xe.messageId="h_exts";var ye,ze,Ae,De,Fe,Qe,Ge,Ie,He,Le,Je,Ee,Re;_.Q=function(a,b){this.b=this.j=this.h="";this.c=null;this.l=this.a="";this.C=!1;var c;a instanceof _.Q?(this.C=_.p(b)?b:a.C,ye(this,a.h),this.j=a.j,this.b=a.b,ze(this,a.c),this.a=a.a,Ae(this,Be(a.g)),_.Ce(this,a.l)):a&&(c=String(a).match(ae))?(this.C=!!b,ye(this,c[1]||"",!0),this.j=De(c[2]||""),this.b=De(c[3]||"",!0),ze(this,c[4]),this.a=De(c[5]||"",!0),Ae(this,c[6]||"",!0),_.Ce(this,c[7]||"",!0)):(this.C=!!b,this.g=new Ee(null,this.C))};
_.Q.prototype.toString=function(){var a=[],b=this.h;b&&a.push(Fe(b,Ge,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(Fe(b,Ge,!0),"@"),a.push((0,window.encodeURIComponent)(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.c,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(Fe(c,"/"==c.charAt(0)?He:Ie,!0));(c=this.g.toString())&&a.push("?",c);(c=this.l)&&a.push("#",Fe(c,Je));return a.join("")};
ye=function(a,b,c){a.h=c?De(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))};ze=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("o`"+b);a.c=b}else a.c=null};Ae=function(a,b,c){b instanceof Ee?(a.g=b,Ke(a.g,a.C)):(c||(b=Fe(b,Le)),a.g=new Ee(b,a.C))};_.R=function(a,b,c){a.g.set(b,c)};_.Ce=function(a,b,c){a.l=c?De(b):b};_.Me=function(a){return a instanceof _.Q?new _.Q(a):new _.Q(a,void 0)};
_.Ne=function(a,b){a instanceof _.Q||(a=_.Me(a));b instanceof _.Q||(b=_.Me(b));var c=a;a=new _.Q(c);var d=!!b.h;d?ye(a,b.h):d=!!b.j;d?a.j=b.j:d=!!b.b;d?a.b=b.b:d=null!=b.c;var e=b.a;if(d)ze(a,b.c);else if(d=!!b.a)if("/"!=e.charAt(0)&&(c.b&&!c.a?e="/"+e:(c=a.a.lastIndexOf("/"),-1!=c&&(e=a.a.substr(0,c+1)+e))),".."==e||"."==e)e="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){c=_.Ba(e,"/");e=e.split("/");for(var f=[],h=0;h<e.length;){var l=e[h++];"."==l?c&&h==e.length&&f.push(""):".."==l?((1<f.length||
1==f.length&&""!=f[0])&&f.pop(),c&&h==e.length&&f.push("")):(f.push(l),c=!0)}e=f.join("/")}d?a.a=e:d=""!==b.g.toString();d?Ae(a,Be(b.g)):d=!!b.l;d&&_.Ce(a,b.l);return a};De=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};Fe=function(a,b,c){return _.q(a)?(a=(0,window.encodeURI)(a).replace(b,Qe),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};Qe=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};
Ge=/[#\/\?@]/g;Ie=/[#\?:]/g;He=/[#\?]/g;Le=/[#\?@]/g;Je=/#/g;Ee=function(a,b){this.b=this.a=null;this.g=a||null;this.c=!!b};Re=function(a){a.a||(a.a=new _.J,a.b=0,a.g&&be(a.g,function(b,c){a.add((0,window.decodeURIComponent)(b.replace(/\+/g," ")),c)}))};Ee.prototype.add=function(a,b){Re(this);this.g=null;a=Se(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};
Ee.prototype.remove=function(a){Re(this);a=Se(this,a);return _.jd(this.a,a)?(this.g=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};Ee.prototype.clear=function(){this.a=this.g=null;this.b=0};var Te=function(a,b){Re(a);b=Se(a,b);return _.jd(a.a,b)};_.g=Ee.prototype;_.g.forEach=function(a,b){Re(this);this.a.forEach(function(c,d){(0,_.v)(c,function(c){a.call(b,c,d,this)},this)},this)};
_.g.X=function(){Re(this);for(var a=this.a.S(),b=this.a.X(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};_.g.S=function(a){Re(this);var b=[];if(_.q(a))Te(this,a)&&(b=_.za(b,this.a.get(Se(this,a))));else{a=this.a.S();for(var c=0;c<a.length;c++)b=_.za(b,a[c])}return b};_.g.set=function(a,b){Re(this);this.g=null;a=Se(this,a);Te(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};
_.g.get=function(a,b){if(!a)return b;a=this.S(a);return 0<a.length?String(a[0]):b};_.Ue=function(a,b,c){a.remove(b);0<c.length&&(a.g=null,a.a.set(Se(a,b),_.Aa(c)),a.b+=c.length)};Ee.prototype.toString=function(){if(this.g)return this.g;if(!this.a)return"";for(var a=[],b=this.a.X(),c=0;c<b.length;c++){var d=b[c],e=(0,window.encodeURIComponent)(String(d));d=this.S(d);for(var f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(h)}}return this.g=a.join("&")};
var Be=function(a){var b=new Ee;b.g=a.g;a.a&&(b.a=new _.J(a.a),b.b=a.b);return b},Se=function(a,b){b=String(b);a.c&&(b=b.toLowerCase());return b},Ke=function(a,b){b&&!a.c&&(Re(a),a.g=null,a.a.forEach(function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),_.Ue(this,c,a))},a));a.c=b};
var Ve;Ve=function(a){return(a=a.exec(_.Ja))?a[1]:""};_.We=function(){if(vb)return Ve(/Firefox\/([0-9.]+)/);if(_.cb||eb||bb)return qb;if(zb)return Va()?Ve(/CriOS\/([0-9.]+)/):Ve(/Chrome\/([0-9.]+)/);if(Ab&&!Va())return Ve(/Version\/([0-9.]+)/);if(wb||xb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.Ja);if(a)return a[1]+"."+a[2]}else if(yb)return(a=Ve(/Android\s+([0-9.]+)/))?a:Ve(/Version\/([0-9.]+)/);return""}();
var Xe=function(a,b){_.K.call(this,a,b);this.U=b};_.u(Xe,_.K);var Ye=function(a){_.B(this,a,"capi_md1571",null,null)};_.u(Ye,_.y);var Ze={pb:0,Cc:1,Ac:2,ob:3,$a:4};Ye.messageId="capi_md1571";var $e=function(a){_.B(this,a,0,null,null)};_.u($e,_.y);var bf=function(){for(var a=10,b=af,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},af="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";_.cf=function(a,b){_.F.call(this);this.j=b||bf();this.c=this.a="";this.b=this.g=null;this.l=a;this.h=new _.O(this);_.I(this,this.h);this.h.listen(window,"message",this.m)};_.u(_.cf,_.F);_.cf.prototype.da=function(a,b,c){this.c=a;this.g=b;this.b=c};
_.cf.prototype.m=function(a){a=a.a;var b=a.origin;this.g&&this.g!=a.source||"*"!=this.c&&this.c!=b?b=!1:this.b?(b=(new _.Q(b)).b,b=_.Ca(b,this.b)?b.length==this.b.length||"."==this.b[0]||"."==b[b.length-1-this.b.length]:!1):b=!0;if(b&&(b=a.data)&&_.q(b)&&"["==b[0]){try{var c=JSON.parse(b);if(!_.ha(c))return}catch(d){return}if(0!=c.length&&"capi_md1571"==c[0]&&(c=new Ye(c),_.z(c,1)==this.j)){b=_.z(c,3);if(!this.a)this.a=b;else if(this.a!=b)return;"*"!=this.c&&this.g||this.da(a.origin,a.source);1==
_.z(c,2)?this.send(2):this.l(c,a)}}};_.cf.prototype.send=function(a,b,c){if(this.a&&this.g){b=b||new Ye;_.A(b,3,this.j);_.A(b,1,this.a);_.A(b,2,a);var d=JSON.stringify(_.D(b)),e=this.g,f=this.c;_.cb?_.Zd(function(){e.postMessage(d,f)}):c?e.postMessage(d,f,c):e.postMessage(d,f)}};
var df=function(a,b,c,d){this.g=_.kc();this.a=new _.cf((0,_.t)(this.h,this),c);this.a.da("*",a,d);this.a.a=b;this.b=new _.Yd(50);this.b.start();_.Ed(this.b,"tick",this.c,!1,this);this.c();a=this.g.a;b=this.C;b=ic(b,b,this);b.g=!0;rc(a,b)};df.prototype.C=function(){_.H(this.a);_.Ld(this.b,"tick",this.c,!1,this);_.H(this.b)};df.prototype.c=function(){this.a.send(1)};df.prototype.h=function(a,b){2==_.z(a,2)&&this.g.b(b.origin)};
var ef=function(a,b,c){_.F.call(this);this.b=a;a=_.z(b,3);b=_.z(b,1);this.a=new _.cf((0,_.t)(this.g,this),b);this.a.a=a;c&&this.a.da(c.origin,c.source);_.I(this,this.a)};_.u(ef,_.F);ef.prototype.send=function(a){var b=new Ye;_.E(b,4,a);this.a.send(Ze.pb,b)};ef.prototype.connect=function(a,b){this.a.da(a,b);this.a.send(Ze.ob)};ef.prototype.g=function(a){_.z(a,2)==Ze.pb&&(a=_.C(a,$e,4),this.b(a))};ef.prototype.c=_.ea;
var gf=function(a,b,c){_.F.call(this);this.h=a;this.b=this.a=this.g=null;c?(this.b=c.ports[0],ff(this)):(this.a=new _.cf(_.ea,_.z(b,1)),a=_.z(b,3),this.a.a=a)};_.u(gf,_.F);gf.prototype.v=function(){gf.w.v.call(this);this.b&&this.b.close();_.H(this.a)};gf.prototype.c=function(){this.g=new _.O(this);_.I(this,this.g);ff(this)};gf.prototype.send=function(a){this.b.postMessage(_.D(a))};
gf.prototype.connect=function(a,b){var c=new window.MessageChannel;this.b=c.port1;ff(this);var d=this.a;this.a=null;c=c.port2;d.da(a,b);d.send(Ze.$a,void 0,[c]);_.H(d)};var ff=function(a){a.b&&a.g&&(a.g.listen(a.b,"message",a.j),a.b.start())};gf.prototype.j=function(a){a=a.a;try{var b=new $e(a.data)}catch(c){return}this.h(b)};
var hf=function(a,b,c){var d=!1;_.p(_.z(b,2))?_.z(b,2)==Ze.$a&&(d=!0):d=zb;return d?new gf(a,b,c):new ef(a,b,c)};var nf,pf;_.jf=function(){_.L.call(this);this.j=null;this.l=!1;this.h=[];this.c=[];_.G(this,this.o,this);this.b=null};_.u(_.jf,_.L);_.jf.prototype.o=function(){for(;this.c.length;)this.c.shift()()};_.lf=function(a){a.o();a.h=[];a.b=new _.wc;a.c.push((0,_.t)(a.b.cancel,a.b));a.l=!1;_.Dc(a.b.b(),function(a){(zd(this.g)||this.F)&&_.kf(this);this.c.push(_.na(_.H,a))},a)};_.jf.prototype.sendMessage=function(a){mf(this,_.D(a))};var mf=function(a,b){if(a.b){var c=new $e;_.A(c,1,b);_.Dc(a.b.b(),function(a){a.send(c)})}};
_.jf.prototype.H=function(){return this};_.jf.prototype.da=function(a,b,c){this.a.da(a,b,c)};_.of=function(a,b,c,d){_.lf(a);nf(a,b,c,d).then(function(a){var d=new Ye;_.A(d,1,a.xc);_.A(d,3,c);d=hf((0,_.t)(this.m,this),d);d.connect(a.origin,b);this.b.g(d)},void 0,a)};nf=function(a,b,c,d){var e=bf();b=(new df(b,c,e,d)).g.a;a.c.push((0,_.t)(b.cancel,b));return b.then(function(a){return{xc:e,origin:a}})};
_.jf.prototype.D=function(a,b){if(_.z(a,2)==Ze.ob||_.z(a,2)==Ze.$a)_.H(this.a),this.a=null,this.b.g(hf((0,_.t)(this.m,this),a,b))};_.jf.prototype.m=function(a){this.h.push(a);this.A()};_.jf.prototype.A=function(){for(;pf(this););};pf=function(a){if(a.G||!a.l||0==a.h.length)return!1;var b=_.z(a.h.shift(),1);a.j&&mf(a.j,b);_.M(a,new Xe(b[0],b));return!0};_.kf=function(a){a.l||(a.l=!0,a.b&&_.Dc(a.b.b(),function(a){a.c();_.Zd(this.A,0,this)},a))}; _.jf.prototype.listen=function(a,b,c,d){_.kf(this);return _.jf.w.listen.call(this,a,b,c,d)};_.jf.prototype.L=function(a,b,c,d){_.kf(this);return _.jf.w.L.call(this,a,b,c,d)};_.jf.prototype.I=function(a){_.kf(this);return _.jf.w.I.call(this,a)};
var qf=function(a){this.b=a;this.c="empty";this.a=null;this.g={}};qf.prototype.ca=function(a){this.c=a;return this};qf.prototype.ra=function(a){this.a=a;return this};qf.prototype.nb=function(a){this.g=_.Oa(a);return this};var rf=function(){};var sf=function(){};_.u(sf,rf);sf.prototype.clear=function(){var a=gd(this.ia(!0)),b=this;(0,_.v)(a,function(a){b.remove(a)})};var tf=function(a){this.a=a};_.u(tf,sf);_.g=tf.prototype;_.g.isAvailable=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};_.g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};_.g.get=function(a){a=this.a.getItem(a);if(!_.q(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};_.g.remove=function(a){this.a.removeItem(a)};
_.g.ia=function(a){var b=0,c=this.a,d=new dd;d.next=function(){if(b>=c.length)throw cd;var d=c.key(b++);if(a)return d;d=c.getItem(d);if(!_.q(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};_.g.clear=function(){this.a.clear()};_.g.key=function(a){return this.a.key(a)};
var uf=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a};_.u(uf,tf);var wf=function(a,b){this.g=a;this.a=[];this.b=null;b&&(this.b=new uf);if(null!=this.b&&this.b.isAvailable()&&(a=this.b.get("__webmonitoring_RateThrottler_history_hourlyRate"),null!=a))try{this.a=JSON.parse(a)||[]}catch(c){}a=!1;_.ha(this.a)||(this.a=[],a=!0);for(;this.a.length>this.g;)this.a.shift(),a=!0;a&&vf(this)},vf=function(a){if(null!=a.b&&a.b.isAvailable())try{a.b.set("__webmonitoring_RateThrottler_history_hourlyRate",_.Zc(a.a))}catch(b){}};
var xf=function(a){_.F.call(this);this.a=a;this.h=!1};_.u(xf,_.F);xf.prototype.setEnabled=function(a){this.h=a};var S=function(a){xf.call(this,a);this.o=100;this.m={};this.O=null;this.g="";this.F=!0;this.j=10;this.b=null;this.c=!1};_.u(S,xf);S.prototype.Cb=function(a){this.F=a;return this};S.prototype.setUseLocalStorage=S.prototype.Cb;S.prototype.vc=function(a){this.j=Math.min(a,100);return this};S.prototype.setMaxErrorsPerHour=S.prototype.vc;S.prototype.Ab=function(a){this.o=a;return this};S.prototype.setGlobalSampling=S.prototype.Ab;S.prototype.rb=function(a,b){this.m[a]=b;return this};
S.prototype.addPerErrorMessageSampling=S.prototype.rb;S.prototype.zb=function(a){this.O=a;return this};S.prototype.setCallback=S.prototype.zb;S.prototype.uc=function(a){this.g=a;return this};S.prototype.setClientId=S.prototype.uc;S.prototype.enable=function(){if(this.h)return!1;this.l=window.onerror;window.onerror=this.A.bind(this);this.setEnabled(!0);return!0};S.prototype.enable=S.prototype.enable;
S.prototype.wb=function(a,b,c,d,e){var f=_.Me(window.location.href);a=null!=e&&null!=e.message?e.message:a;var h;if(h=!_.ja(this.O)||this.O(f.a,a,b,c,d,e))if(h=this.c){h=Object.keys(this.m);for(var l=100,n=0;n<h.length;++n){var r=h[n];(new RegExp(r)).test(a)&&(l=this.m[r])}if(h=(100*Math.random()).toFixed(6)>=this.o*l/100?!1:!0){0<=this.j&&null===this.b&&(this.b=new wf(this.j,this.F));if(null===this.b)h=!1;else{a:{h=this.b;l=(0,_.m)();if(h.a.length==h.g)if(h.a[0]<l-36E5)h.a.shift();else{h=!1;break a}h.a.push(l);
vf(h);h=!0}h=!h}h=!h&&this.c}}h&&(h=_.Oa(this.a.g),h.url=f.a,h.type="JavascriptError",h.error_message=a,l="Other",bb?l="Opera":_.cb?l="Internet Explorer":vb?l="Firefox":zb?l="Chrome":Ab&&(l="Safari"),h.browser=l,h.browser_version=_.We,h.os=_.Ya()?"Chrome OS":_.x("Linux")?"Linux":_.Xa()?"Windows":_.x("Android")?"Android":Ua()?"iPhone":_.x("iPad")?"iPad":_.x("iPod")?"iPod":_.Wa()?"Mac":"Unknown",l=_.Ja,n="",_.Xa()?(n=/Windows (?:NT|Phone) ([0-9.]+)/,n=(l=n.exec(l))?l[1]:"0.0"):Va()?(n=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,
n=(l=n.exec(l))&&l[1].replace(/_/g,".")):_.Wa()?(n=/Mac OS X ([0-9_.]+)/,n=(l=n.exec(l))?l[1].replace(/_/g,"."):"10"):_.x("Android")?(n=/Android\s+([^\);]+)(\)|;)/,n=(l=n.exec(l))&&l[1]):_.Ya()&&(n=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,n=(l=n.exec(l))&&l[1]),h.os_version=n||"",null!=this.a.a&&(h.channel=this.a.a),_.Da(this.g)||(h.guid=this.g),null!=b&&(h.src=b),null!=c&&(h.line=c),null!=d&&(h.column=d),h.prod=this.a.b,h.ver=this.a.c,c=null!=e?_.Ga(e.stack):"",b=yf(h),_.Da(a)||(d=c.split("\n"),
-1<d[0].indexOf(a)&&(d.splice(0,1),c=d.join("\n"))),zf(this,"https://clients2.google.com/cr/staging_report",b,c),f={product:this.a.b,url:f.a,js_errors_count:"1"},a=_.Ga(this.a.a),_.Da(a)||(f.version=a),zf(this,"https://clients2.google.com/cr/staging_perf",yf(f)))};S.prototype.reportError=S.prototype.wb;S.prototype.A=function(a,b,c,d,e){this.wb(a,b,c,d,e);null!=this.l&&_.ja(this.l)&&this.l(a,b,c,d,e)};
var yf=function(a){var b="",c;for(c in a)b+=_.Da(b)?"?":"&",b+=c+"="+(0,window.encodeURIComponent)(a[c]);return b},zf=function(a,b,c,d){d=d||"";var e=_.Da(d)?{}:{"Content-Type":"text/plain"};_.ge(b+c,a.I.bind(a,b),"POST",d,e,6E4,!0)};S.prototype.I=function(a,b){_.pe(b.target)};
var Af=function(a){xf.call(this,a);this.O=null;this.b=0};_.u(Af,xf);Af.prototype.zb=function(a){this.O=a;return this};var Bf=[{age:6E4,name:"1m"},{age:15E5,name:"25m"},{age:36E5,name:"1h"},{age:36E6,name:"10h"}];Af.prototype.enable=function(){if(this.h)return!1;if(window.performance&&window.performance.memory){var a=new _.Yd(6E4);_.I(this,a);var b=new _.O(this);_.I(this,b);b.listen(a,"tick",this.g);a.start();this.setEnabled(!0);return!0}return!1};
Af.prototype.g=function(){this.b+=6E4;for(var a="",b=0;b<Bf.length;++b)if(this.b==Bf[b].age){a=Bf[b].name;break}if(""!=a){b=Cf.test(_.Ja)?"":"32_bit_";var c=window.performance.memory;if(c.totalJSHeapSize&&c.usedJSHeapSize){a=[{name:"total_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Total JS heap (MB)",value:Math.round(c.totalJSHeapSize/1048576)},{name:"used_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Used JS heap (MB)",value:Math.round(c.usedJSHeapSize/1048576)}];b=_.Me(window.location.href).a;
c="?product="+(0,window.encodeURIComponent)(this.a.b)+"&url="+(0,window.encodeURIComponent)(b);var d=_.Ga(this.a.a);_.Da(d)||(c+="&version="+(0,window.encodeURIComponent)(d));for(d=0;d<a.length;++d)c+="&"+(0,window.encodeURIComponent)(a[d].name)+"="+a[d].value,_.ja(this.O)&&this.O(b,a[d].displayName,a[d].value);_.ge("https://clients2.google.com/cr/staging_perf"+c,Df,"POST","",null,6E4,!0)}}};var Df=function(a){_.pe(a.target)},Cf=/(x86_64|Win64)/;
var Ef=function(a){_.F.call(this);this.b=new qf(a);this.a={}};_.u(Ef,_.F);_.oa("webmonitoring.Monitoring",Ef);Ef.prototype.ca=function(a){this.b.ca(a);return this};Ef.prototype.setVersion=Ef.prototype.ca;Ef.prototype.ra=function(a){this.b.ra(a);return this};Ef.prototype.setChannel=Ef.prototype.ra;Ef.prototype.nb=function(a){this.b.nb(a);return this};Ef.prototype.setContext=Ef.prototype.nb;Ef.prototype.Na=function(){null!=this.a[2]||(this.a[2]=new S(this.b));return this.a[2]}; Ef.prototype.createJsErrorsReporter=Ef.prototype.Na;
var Ff=function(a){Ef.call(this,a)};_.u(Ff,Ef);Ff.prototype.ca=function(a){return Ff.w.ca.call(this,a)};Ff.prototype.ra=function(a){return Ff.w.ra.call(this,a)};Ff.prototype.Na=function(){var a=Ff.w.Na.call(this);a.c=!0;return a};_.Gf=function(){var a=new Ff("Google_Hangouts_Chrome");a.ra(window.chrome.runtime.id);a.ca(window.chrome.runtime.getManifest().version);null!=a.a[1]||(a.a[1]=new Af(a.b));a.a[1].enable();a.Na().Cb(!1).Ab(100).rb("Script error.",0).enable()};
}catch(e){_._DumpException(e)}
/* _Module_:host */
try{
var jp=function(a,b){_.lc(a,null,b,void 0)},kp=function(a){_.B(this,a,"uv_r_hrd",null,null)};_.u(kp,_.y);kp.messageId="uv_r_hrd";
var lp=function(a,b){return a.g.get(b)},mp=function(a,b){a.j=b;_.G(a,function(){this.j=null},a);_.kf(a)},np=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.ia(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}},op=function(a){var b=new _.jf;_.lf(b);b.a=new _.cf((0,_.t)(b.D,b),a);b.a.da("*",void 0,void 0);b.c.push(_.na(_.H,b.a));return b};
var pp=function(a){this.a=a;_.cb||(delete this.a.lpu,delete this.a.ppu)},qp=["cn","tp"],rp=function(a,b){if(_.ja(window.document.postMessage)||_.ja(window.postMessage)||_.cb&&window.postMessage)var c=1;else if(_.fb)c=2;else{var d;if(d=_.cb){d=!1;try{c=window.opener,window.opener={},d=_.$a(window,"opener"),window.opener=c}catch(e){}}c=d?6:4}d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new pp(d)};_.oa("GTalk_IFrameChannelConfig.build",rp);
var sp=function(){},vp=function(a){var b=a.na,c=function(a){c.w.constructor.call(this,a);var b=this.Z.length;this.a=[];for(var d=0;d<b;++d)this.Z[d].Rc||(this.a[d]=new this.Z[d](a))};_.u(c,b);for(var d=[];a;){if(b=a.na){b.Z&&np(d,b.Z);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.ja(e[f])&&e[f]!==b){var h=!!e[f].Rb,l=tp(f,e,d,h);(h=up(f,e,l,h))&&(c.prototype[f]=h)}}a=a.w&&a.w.constructor}c.prototype.Z=d;return c},tp=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||
(e.push(f),!d));++f);return e},up=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.Z[c[0]].prototype[a].apply(this,arguments)}:b[a].Tb?e=function(b){a:{var d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=this.a[c[e]];if(f=f?f[a].apply(f,d):this.Z[c[e]].prototype[a].apply(this,d)){d=f;break a}}d=!1}return d}:b[a].Sb?e=function(b){a:{var d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=
this.a[c[e]];f=f?f[a].apply(f,d):this.Z[c[e]].prototype[a].apply(this,d);if(null!=f){d=f;break a}}d=void 0}return d}:b[a].hc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var f=this.a[c[e]];f?f[a].apply(f,d):this.Z[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],f=0;f<c.length;++f){var r=this.a[c[f]];e.push(r?r[a].apply(r,d):this.Z[c[f]].prototype[a].apply(this,d))}return e}:d||b[a].Tb||b[a].Sb||b[a].hc? e=null:e=wp;return e},wp=function(){return[]};sp.prototype.h=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};var xp=function(a){(a?a:function(){}).Rb=!0};
var yp=function(){};_.u(yp,sp);yp.prototype.b=function(a){return a};xp(yp.prototype.b);yp.prototype.g=function(){return!0};xp(yp.prototype.g);var zp=function(a){_.B(this,a,0,null,null)};_.u(zp,_.y);var Ap=function(a,b){var c=new zp;_.A(c,1,b);_.A(c,2,a);return c},Bp=Ap("?",0),Cp=Ap("q",1),Dp=Ap("<",2),Ep=Ap(">",3),Fp=Ap("~",4),Gp=Ap("s",5),Hp={Bc:Bp,Kc:Cp,Ec:Dp,Fc:Ep,Dc:Fp,Mc:Gp};var Ip=function(a){_.B(this,a,"h_cc",null,null)};_.u(Ip,_.y);var Jp=function(a){_.B(this,a,0,null,null)};_.u(Jp,_.y);var Kp=function(a){_.B(this,a,0,null,null)};_.u(Kp,_.y);var Lp=function(a){_.B(this,a,0,null,null)};_.u(Lp,_.y);var Mp=function(a){_.B(this,a,0,null,null)};_.u(Mp,_.y);Ip.messageId="h_cc";var Np=function(a,b){_.A(a,3,b)},Op=function(a,b){_.A(a,4,b)},Pp=function(a,b){_.A(a,11,b)};
var Qp=function(a){_.B(this,a,"ci:ec",null,null)};_.u(Qp,_.y);Qp.messageId="ci:ec";var Rp=function(a){return this.ib.h(a)};var Sp=function(){this.a=window.document||{cookie:""}};_.g=Sp.prototype;_.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("B`"+a);if(/[;\r\n]/.test(b))throw Error("C`"+b);_.p(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.m)()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
_.g.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(";"),e=0,f;e<d.length;e++){f=(0,_.Ea)(d[e]);if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.g.remove=function(a,b,c){var d=_.p(this.get(a));this.set(a,"",0,b,c);return d};_.g.X=function(){return Tp(this).keys};_.g.S=function(){return Tp(this).values};_.g.clear=function(){for(var a=Tp(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])}; var Tp=function(a){a=(a.a.cookie||"").split(";");for(var b=[],c=[],d,e,f=0;f<a.length;f++)e=(0,_.Ea)(a[f]),d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
var Up=function(a,b){if(!this.ib){for(var c=this.constructor;c&&!c.na;)c=c.w&&c.w.constructor;c.na.ub||(c.na.ub=vp(c));this.ib=new c.na.ub(this);this.h||(this.h=Rp)}var d=this.ib.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(_.Ba(d,"https://talkgadget.google.com/talkgadget/")){c=(new Sp).get("WCSDBG","");c=c.split(";")[0];c=c.split("|")[0];var e=["plus.google.com"],f=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<c.length&&!_.wa(e,c)&&f.test(c)&&(d=_.Me(d),d=_.Me("https://"+
c+d.a).toString())}this.g=d;this.c=b||new Qp;a.notificationsOnly&&_.A(this.c,1,!0);this.b="0";null!=a.authUser?this.b=a.authUser:(b=lp(new _.Q(window.location.href),"authuser"),null!=b&&(this.b=b));this.o=a.clientUrl||"notifierclient";b=lp(_.Me(this.o),"authuser");null!=b&&(this.b=b);this.bb=a.propertyName||"Google Talk";this.I=a.cssUrl;this.locale=a.locale;this.j=a.debug;this.La=a.userJid;this.Ia=a.uiVersion;this.ac=null!=a.rosterExpanded?a.rosterExpanded:!0;this.W=a.hostLogMinValue;this.xa=a.hideChat;
this.Ub=a.refresh;this.P=a.hideProfileCard;this.V=a.hideStatusMsgs;this.T=a.hideRosterOptions;this.N=a.hideRecentConversations;this.M=a.hideOTR;this.cb=a.hostServerMessageCallback||!1;this.ba=a.isCentralRoster;this.hb=a.isFullFrame||!1;this.Xb=a.rosterClass||"talk_roster";this.bc=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.wa=a.parentToken;_.p(a.isRtl)||_.Ic.test(this.locale);
this.l=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var h in Hp)b.push(_.D(Hp[h]))}this.D=a.entityId;this.Ja=a.useQuasarPanels||!1;this.silent=a.silent||!1;this.gb=a.ignoreCentralRoster||!1;this.Wb=a.lazy||!1;this.Pa=a.handleProfileLinks||!1;this.ha=a.hostSettings;this.m=a.screen;this.A=a.docsConfig;this.Vb=a.jsmode;this.va=a.moleWidth;this.ua=a.moleHeight;this.ta=a.minimizedMoleHeight||36;this.dc=a.derp;this.Ha=window.location.protocol+"//"+window.location.host;this.C="";this.J=a.optOutAllowed;
this.L=a.legacyTalkSignedIn;this.Ka=a.useSpareMole;this.F=a.conversationId};yp.w||_.u(yp,sp);Up.na=yp;
var Wp=function(a){var b={},c=_.Fb(a,1,"hangouts.google.com"),d="";0>c.indexOf("://")&&(d="https://",0<=c.indexOf(":")&&23!=_.z(a,2)&&27!=_.z(a,2)&&(d="http://"));b.clientBaseUrl=d+c+"/webchat/u/"+_.Fb(a,8,"0")+"/";b.clientUrl="load";b.authUser=_.Fb(a,8,"0");b.propertyName=Vp(_.z(a,2));b.locale=_.z(a,4);b.hideProfileCard=!0;b.parentToken=_.z(a,3);b.isRtl=_.Fb(a,6,!1);b.lazy=_.Fb(a,7,!1);b.entityId=_.z(a,9);b.hostSettings=_.z(a,5);b.jsmode=_.z(a,11);b.isFullFrame=_.Fb(a,13,!1);b.rosterId=_.Fb(a,12,
"talk_roster");b.rosterIframeId=_.Fb(a,12,"talk_roster");b.rosterIframeIdB=_.Fb(a,15,"gtn-roster-iframe-id-b");b.derp=!!_.Fb(a,16,!1);c=_.C(a,Mp,14);null!=c&&(b.isCentralRoster=_.Fb(c,1,!1),b.useQuasarPanels=_.Fb(c,2,!1));c=_.C(a,Jp,10);null!=c&&(b.moleManagerLeftMargin=_.z(c,1),b.moleManagerMiddleMargin=_.z(c,2),b.moleManagerRightMargin=_.z(c,3),b.moleManagerNoMoleAreaMargin=_.z(c,4),b.moleManagerBoundingElementId=_.z(c,5),b.moleWidth=_.z(c,6),b.moleHeight=_.z(c,7),b.minimizedMoleHeight=_.z(c,8));
c=_.C(a,Kp,18);null!=c&&(b.optOutAllowed=_.Fb(c,1,!0),d=_.C(c,Lp,3),null!=d&&(b.legacyTalkSignedIn=_.Fb(d,1,!0)),c=_.z(c,4),null!=c&&(b.useSpareMole=c));b.uiVersion=2;b.hideStatusMsgs=!0;b.hideRecentConversations=!0;c=new Qp;_.A(c,2,!0);_.A(c,1,!0);_.A(c,3,!1);b.endpointConfig=c;b.ignoreAutomatedRoster=_.Fb(a,17,!1);b.conversationId=_.z(a,19);return b},Vp=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";
case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 36:return"StartPage"}},Xp=function(a,b){if(-1!=a.indexOf("talkgadget.")){var c=_.Me(a),d=c.a;if(0<=d.indexOf("/u/"))return a;a=d.lastIndexOf("_/");if(0>a||a!=d.length-2)d+="_/";c.a="/u/"+b+d;return c.toString()}return a};
var Yp=function(a,b,c,d,e){_.F.call(this);this.a=a;this.b=d||window.document;this.g=new _.O(this);_.I(this,this.g);var f=_.Ja;d=new _.Q(a.g+a.o);_.Fb(a.c,2,!1)||(_.R(d,"ts","0"),_.R(d,"re",a.ac),_.R(d,"ref",a.Ub));_.R(d,"client","sm");_.R(d,"prop",a.bb);_.R(d,"nav","true");_.R(d,"fid",a.a);a.j&&_.R(d,"debug",a.j);_.R(d,"os",_.hb);_.R(d,"stime",c);a.xa&&_.R(d,"hc",a.xa);for(c=0;c<qp.length;++c);b=_.Zc(b.a);_.R(d,"xpc",b);_.R(d,"ec",_.Zc(_.D(a.c)));a.m&&_.R(d,"screen",a.m);-1!=f.indexOf("MSIE")&&_.R(d,
"ua",f);a.wa&&_.R(d,"pvt",a.wa);a.cb&&_.R(d,"hsmc","true");_.p(a.W)&&_.R(d,"logl",a.W);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.R(d,"href",b.join("?")));b=new _.Q(window.location.href);"false"==lp(b,"uacheck")&&_.R(d,"uacheck",!1);(f=a.Vb)&&_.R(d,"jsmode",f);(f=lp(b,"cssmode"))&&_.R(d,"cssmode",f);(f=lp(b,"convid"))&&_.R(d,"convid",f);if(f=b.g.S("convp"))_.ha(f)||(f=[String(f)]),_.Ue(d.g,"convp",f);(f=lp(b,"smexp"))&&_.R(d,"smexp",
f);f=b.g.S("mods");a.Wb&&f.push("lazy");e&&(f=_.za(f,e));0<f.length&&_.R(d,"mods",f.join(","));if(!a.g||0>a.g.indexOf("/u/"))(e=lp(b,"authuser"))?_.R(d,"authuser",e):null!=a.b&&_.R(d,"authuser",a.b);e=lp(b,"eid");_.Da(_.Ga(e))||_.R(d,"eid",e);_.Da(_.Ga(this.a.D))||_.R(d,"eid",this.a.D);null!=this.a.l&&_.R(d,"pos",this.a.l);_.p(a.Ia)&&_.R(d,"uiv",this.a.Ia);a.I&&_.R(d,"css",a.I);e=a.locale||lp(b,"hl");null!=e&&_.R(d,"hl",e);_.p(a.La)&&_.R(d,"uj",a.La);null!=a.P&&_.R(d,"hpc",a.P);null!=a.V&&_.R(d,"hsm",
a.V);null!=a.T&&_.R(d,"hro",a.T);null!=a.N&&_.R(d,"hrc",a.N);null!=a.M&&_.R(d,"hotr",a.M);null!=a.ba&&_.R(d,"pop",a.ba);_.R(d,"pal","1");null!=a.Ja&&_.R(d,"uqp",a.Ja);null!=a.J&&_.R(d,"gooa",a.J);null!=a.L&&_.R(d,"gltsi",a.L);null!=a.Ka&&_.R(d,"gusm",a.Ka);null!=a.silent&&_.R(d,"sl",a.silent);a.gb&&_.R(d,"icr","1");a.Pa&&_.R(d,"hpl","1");a.ha&&_.R(d,"hs",a.ha);a.A&&_.R(d,"dc",_.Zc(_.D(a.A)));null!=a.va&&_.R(d,"molew",a.va);null!=a.ua&&_.R(d,"moleh",a.ua);null!=a.ta&&_.R(d,"mmoleh",a.ta);a.dc&&_.R(d,
"derp","1");a.C&&_.R(d,"fcho",a.C);null!=a.Ha&&_.R(d,"two",a.Ha);null!=a.F&&_.R(d,"convid",a.F);_.R(d,"host","1");_.R(d,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.m)()).toString(36));this.c=d.toString()};_.u(Yp,_.F);Yp.prototype.install=function(a,b){Zp(this,a,b,_.ea)};
var Zp=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.Xb,a.b.body.appendChild(e));a=(0,_.t)(function(){var a="";this.a.hb||(a="height:400px");var b=_.Wc(new _.Vc(this.b),"IFRAME");_.Tc(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a,"aria-hidden":"true",allow:"microphone *; autoplay *"});_.Rc("talk_loading_msg",e)||_.Uc(e);e.appendChild(b);var l=this.b.getElementById(this.a.a);_.se(this.g,l,["load","error"],function(a){l.contentWindow.postMessage("AllowFrame: Chat", "*");d(a)});l.src=this.c.toString();c()},a);window.setTimeout(a,0)};
var $p=function(a){var b=_.Ne(_.z(a,2),"/webchat/extension-start");_.z(a,5)&&_.R(b,"e",_.z(a,5));return new _.fc(function(a,d){_.ge(b,function(b){_.pe(b.target)||d();try{var c=b.target;try{var e=c.a?c.a.responseText:""}catch(n){e=""}var l=JSON.parse(e);a(new _.xe(l))}catch(n){d(n.message)}})})};
var bq=function(){var a=this;_.O.call(this);_.P("Starting ...");this.listen(window,"unload",this.$);this.b=new _.te(JSON.parse((0,window.decodeURI)(window.location.hash.substr(1))));this.a=op(_.z(this.b,1));_.I(this,this.a);this.g=new _.jf;_.I(this,this.g);jp($p(this.b).then(function(b){return aq(a,b)}),function(a){_.P("Failed to start : %s.",a||"")})},cq;_.u(bq,_.O);
var aq=function(a,b){if(!a.G&&(a.a.sendMessage(b),_.z(b,1))){var c=new Ip,d=_.Me(_.z(a.b,2)),e=d.b;null!=d.c&&(e+=":"+d.c);_.A(c,1,e);_.A(c,2,27);_.A(c,13,!0);_.A(c,17,!0);Np(c,_.z(b,1));Pp(c,_.z(a.b,4));Op(c,_.z(a.b,3)||"en");b=Wp(c);var f=new Up(b,b.endpointConfig);f.g=Xp(f.g,f.b);f.C=window.location.origin;f.a="gtn-roster-iframe-id-q";b=rp(f.g,f.a);b=new Yp(f,b,(0,_.m)(),window.document);_.I(a,b);Zp(b,f.bc,function(){},function(){_.of(a.g,window.document.getElementById(f.a).contentWindow,"31ACFC0_", "google.com");mp(a.g,a.a);mp(a.a,a.g);a.a.sendMessage(new kp)})}};_.oa("default_host._DumpException",function(a){return window.console.error(a.stack)});_.Gf();if(!cq||cq.G)cq=new bq;

}catch(e){_._DumpException(e)}
/* _GlobalSuffix_ */
}).call(this,this.default_host);
// Google Inc.
